// What every session shares, per formula: warm-up, core and prevention block, cool-down,
// the phases, and the Guide (explanations only, no exercise tables).

const niveaux = [
  { h3: "Choisir ton niveau" },
  { table: { head: ["Niveau", "Pour qui", "Dans les séances"], rows: [
    ["Niveau 1", "Tu débutes : peu ou pas de préparation physique jusqu'ici", "Nombre de séries le plus bas, versions « plus facile »"],
    ["Niveau 2", "Tu as quelques bases : une saison de musculation ou de préparation", "Nombre de séries du milieu"],
    ["Niveau 3", "Tu as de l'expérience : plusieurs saisons d'entraînement régulier", "Nombre de séries le plus haut, versions avancées"],
  ] } },
  { p: "Dans tes séances, « 2-4 × 8 » veut dire 2 séries (niveau 1), 3 séries (niveau 2) ou 4 séries (niveau 3) de 8 répétitions. « 2-3 × 8 » : 2 séries aux niveaux 1 et 2, 3 au niveau 3." },
  { h3: "Régler l'intensité : l'échelle d'effort" },
  { table: { head: ["Note", "Ressenti", "Repère"], rows: [
    ["5-6", "Facile à modéré", "Tu pourrais encore faire 4 à 5 répétitions"],
    ["7-8", "Difficile mais contrôlé", "Il te reste 2 à 3 répétitions en réserve"],
    ["9", "Très difficile", "Plus qu'une répétition possible"],
    ["10", "Maximal", "À éviter dans ce programme"],
  ] } },
  { h3: "Moins de 15 ans (filles) ou de 16 ans (garçons)" },
  { p: "Le programme est le même, avec quelques règles pour que les charges restent adaptées à ton âge :" },
  { ul: ["**Pas de séries lourdes** de 1 à 5 répétitions : prends une charge que tu pourrais soulever 10 à 12 fois, et fais-en 6 à 8.", "**Garde toujours au moins 3 répétitions en réserve** : jamais de série jusqu'à l'échec.", "**La technique avant le poids** : tu n'ajoutes de la charge que si le mouvement reste parfait du début à la fin de la série.", "**La barre seulement avec un adulte** qui connaît le mouvement (coach, préparateur, parent formé).", "Les sauts, les sprints et la prévention ne changent pas.", "En salle, chaque exercice avec charge indique sa version pour ton âge, sous « Moins de 15 ans (filles) ou de 16 ans (garçons) »."] },
  { warn: "Douleur vive, articulation qui lâche, vertige : arrête l'exercice. Une gêne qui dure plus de 48 heures ou qui revient à chaque séance doit être vue par un professionnel de santé." },
];

// Equipment, depending on where the program is done (home or gym, chosen at checkout).
const materiel = [
  { h3: "Matériel" },
  { lieu: "maison", p: "Ton programme est fait pour la maison : poids du corps et objets du quotidien (sac à dos lesté, chaise, canapé, table solide, bouteille d'eau). Un **élastique de résistance** (léger, moyen et fort) est conseillé : les fiches exercices indiquent la variante élastique quand elle existe." },
  { lieu: "salle", p: "Ton programme est fait pour la salle de sport : haltères, barre, banc, poulies, caisse de pliométrie, médecine-ball. Pour la course, utilise un **tapis de course incurvé** (non motorisé, en forme de courbe : c'est toi qui fais tourner la bande) si ta salle en a un ; sinon, chaque fiche indique une alternative (vélo d'assaut, rameur)." },
];

const documents = (seances) => [
  { table: { head: ["Tu as reçu", "À quoi ça sert"], rows: [
    ["Ce guide", "Comprendre le programme : fonctionnement, planning, progression, règles"],
    ["Tes séances", `Toutes tes séances écrites en entier, dans l'ordre, avec ${seances} et la fiche illustrée de chaque exercice`],
    ["Option course (si choisie)", "Tes séances de course, en plus"],
  ] } },
  { note: "**Le jour de la séance, tu n'as besoin que du document « Tes séances »** : tout y est, de l'échauffement au retour au calme. Ce guide sert à comprendre le programme, lis-le une fois en entier avant de commencer." },
];

const retourAuCalme = "2 minutes de marche, puis des étirements légers de 20 à 30 secondes, sans forcer : fléchisseurs de hanche, quadriceps, ischios, mollets, pectoraux et épaules.";

export const formules = {
  "pre-saison": {
    name: "Pré-saison",
    tag: "Avant la saison",
    color: "#FF7A59",
    duree: "8 semaines",
    frequence: "3 séances + 1 bonus",
    seance: "45 à 60 min",
    echauffement: { title: "Échauffement · 10 à 12 min", rows: [
      ["footing-dynamique", "3 min", ""], ["fente-rotation", "6 par côté", ""], ["ouverture-hanche", "8 par côté", ""], ["pont-fessier", "2 × 10", "15 s"],
      ["planche", "2 × 20 s", "15 s"], ["equilibre", "2 × 20 s par jambe", ""], ["saut-reception", "2 × 5", "20 s"], ["accelerations", "3 passages", "retour en marchant"],
    ] },
    gainage: {
      A: [["planche", "2-4 × 30 s", "30 s"], ["gainage-lateral", "2-3 × 20 s par côté", "20 s"], ["nordic", "2-3 × 4", "60 s"]],
      B: [["dead-bug", "2-3 × 8 par côté", "30 s"], ["ytw", "2-3 × 8", "30 s"], ["equilibre-balle", "2 × 30 s par jambe", "20 s"]],
      C: [["pont-une-jambe", "2-3 × 10 par jambe", "30 s"], ["copenhague", "2-3 × 15 s par côté", "30 s", "version genou"], ["rotation-externe", "2-3 × 12 par bras", "30 s"]],
    },
    bonus: { title: "Séance D (bonus, facultative) · 20 min", rows: [["planche", "2 × 30 s", "30 s"], ["gainage-lateral", "2 × 20 s par côté", "20 s"], ["nordic", "2 × 3", "60 s"], ["hanches-9090", "1 × 8 par côté", ""], ["cheville-mur", "1 × 10 par côté", ""], ["rotation-thoracique", "1 × 8 par côté", ""]] },
    retourAuCalme,
    phases: [
      { id: "bases", title: "Semaines 1-2 · Mise en route", texte: "Réhabituer le corps à l'effort et apprendre les gestes. Effort 5-6 sur 10." },
      { id: "force", title: "Semaines 3-5 · Montée en charge", texte: "Monter progressivement les charges. La semaine 5 est la plus chargée. Effort 7-8 sur 10." },
      { id: "explo", title: "Semaines 6-7 · Intensité", texte: "Moins de volume, plus de vitesse : chaque répétition de qualité maximale. Effort 7-8 sur 10." },
    ],
    affutage: { title: "Semaine 8 · Affûtage", texte: "Refais les séances A, B et C des semaines 6-7 en faisant **la moitié des séries**, avec la même intensité. Tu aborderas la reprise avec ton club en pleine forme." },
    guide: [
      { h2: "Avant de commencer" },
      { p: "8 semaines pour reprendre sur des bases solides avant la reprise avec ton club. Ce guide t'explique comment fonctionne ton programme." },
      { h2: "Quand commencer ?" },
      { p: "Fais ton programme pendant les **2 mois qui précèdent le début de la saison** : en général en juillet et en août, pour une saison qui démarre début septembre." },
      { table: { head: ["Ton club", "Semaines 1 à 4", "Semaines 5 à 8"], rows: [
        ["Fait une prépa physique à la reprise (par exemple début août)", "Seul(e), avant la reprise du club", "En parallèle des entraînements de prépa physique du club"],
        ["Ne fait pas de prépa physique", "Seul(e), à partir de début juillet", "Seul(e), jusqu'au début de la saison"],
      ] } },
      { note: "**En parallèle du club :** garde 48 heures entre deux séances A, B ou C, pas de séance la veille d'un entraînement collectif très intense, et allège (moins de séries) si la fatigue s'accumule. Lance ton accès aux animations le jour de ta première séance." },
      ...documents("l'échauffement, ton ou tes objectifs, le gainage et le retour au calme"),
      ...materiel,
      ...niveaux,
      { h2: "Ta semaine type" },
      { p: "Chaque semaine compte **3 séances (A, B et C)**, plus une **séance D bonus** facultative, courte, centrée sur la prévention et la mobilité." },
      { table: { head: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"], rows: [["Séance A", "Repos ou club", "Séance B", "Repos ou club", "Séance D (bonus)", "Séance C", "Repos"]] } },
      { p: "C'est un exemple : adapte-le à ton emploi du temps en respectant ces règles." },
      { ul: ["Au moins **48 heures** entre deux séances A, B ou C.", "Au moins **un jour de repos complet** par semaine.", "Pas de séance la veille d'un match amical ou d'un entraînement collectif très intense.", "Une séance ratée ne se rattrape pas en doublant : reprends simplement à la séance suivante."] },
      { h2: "Comment se déroule une séance" },
      { table: { head: ["Étape", "Durée", "À quoi ça sert"], rows: [
        ["1. Échauffement", "10-12 min", "Préparer le corps et réduire le risque de blessure. Le même à chaque séance."],
        ["2. Premier bloc", "15-20 min", "Ton premier objectif. Explosivité et Puissance passent toujours en premier, quand tu as toute ton énergie."],
        ["3. Deuxième bloc", "15-20 min", "Ton deuxième objectif. Si tu as choisi un seul objectif, ce bloc le travaille sous un autre angle."],
        ["4. Gainage et prévention", "5-8 min", "Renforcer les zones les plus exposées au handball : genoux, chevilles, épaules, ischios, adducteurs."],
        ["5. Retour au calme", "5 min", "Marche et étirements légers."],
      ] } },
      { note: "**Pourquoi un échauffement si complet ?** Une grande étude menée dans 120 clubs de handball norvégiens a montré qu'un échauffement travaillant la course, l'équilibre et la réception des sauts divisait environ par deux les blessures du genou et de la cheville (Olsen et al., BMJ, 2005)." },
      { h2: "La progression sur 8 semaines" },
      { table: { head: ["Semaine", "Phase", "Ce qu'on cherche", "Volume", "Effort"], rows: [
        ["1", "Mise en route", "Réhabituer le corps à l'effort, apprendre les gestes", "Faible", "5-6"],
        ["2", "Mise en route", "Idem, un peu plus de travail", "Faible à moyen", "6"],
        ["3", "Montée en charge", "Monter progressivement les charges", "Moyen", "7"],
        ["4", "Montée en charge", "Continuer la montée", "Moyen à élevé", "7-8"],
        ["5", "Montée en charge", "Semaine la plus chargée", "Élevé", "8"],
        ["6", "Intensité", "Moins de volume, plus de vitesse", "Moyen", "7-8"],
        ["7", "Intensité", "Qualité maximale de chaque répétition", "Moyen", "8"],
        ["8", "Affûtage", "Récupérer en gardant l'intensité", "Réduit de moitié", "6-7"],
      ] } },
      { note: "**Semaine 8 : moins, c'est mieux.** Tu fais la moitié des séries, avec la même qualité, pour aborder la reprise en pleine forme." },
      { h2: "Suivre tes séances" },
      { p: "Note chaque séance : c'est le meilleur moyen de progresser et de repérer la fatigue." },
      { table: { head: ["Date", "Séance", "Effort ressenti (/10)", "Forme du jour (/5)", "Gênes ou remarques"], rows: Array.from({ length: 8 }, () => [" ", " ", " ", " ", " "]) } },
      { ul: ["Forme du jour à 1 ou 2 sur 5 deux séances de suite : allège (moins de séries) ou prends un jour de repos en plus.", "Tout est facile (effort à 5 alors que 7-8 est prévu) : prends le niveau au-dessus."] },
      { h2: "Et après ?" },
      { p: "À la fin des 8 semaines, la saison commence. Pour garder ce que tu as construit sans fatiguer tes jambes avant les matchs, tu peux enchaîner avec la **1re partie de saison** : 2 séances courtes par semaine jusqu'aux vacances de Noël." },
      { p: "Une question sur le programme ? Réponds simplement à l'email qui t'a envoyé ce document." },
    ],
  },

  "premiere-partie": {
    name: "1re partie de saison",
    tag: "Septembre à Noël",
    color: "#2EC4B6",
    duree: "18 semaines",
    frequence: "2 séances par semaine",
    seance: "30 à 40 min",
    echauffement: { title: "Échauffement · 8 min", rows: [
      ["footing-dynamique", "2 min", ""], ["fente-rotation", "5 par côté", ""], ["pont-fessier", "1 × 10", ""], ["planche", "1 × 20 s", ""],
      ["equilibre", "20 s par jambe", ""], ["saut-reception", "1 × 5", ""], ["accelerations", "2 passages", "retour en marchant", "70 %, puis 85 %"],
    ] },
    gainage: {
      "1": [["nordic", "2 × 3-5", "60 s"], ["copenhague", "2 × 15 s par côté", "30 s", "version genou"], ["planche", "1-2 × 30 s", "30 s"]],
      "2": [["rotation-externe", "2 × 12 par bras", "30 s"], ["ytw", "2 × 8", "30 s"], ["equilibre-balle", "2 × 20 s par jambe", "20 s"]],
    },
    retourAuCalme,
    blocs: [
      { id: "entree", title: "Semaines 1 à 4 · Entrer dans la saison", texte: "Les matchs reprennent : on garde la force et l'explosivité de l'été sans fatiguer les jambes. Effort 6-7 sur 10. **Semaine 4 allégée** : une série en moins sur chaque exercice." },
      { id: "intensite", title: "Semaines 5 à 8 · Entretenir en intensité", texte: "Peu de séries, mais lourd et rapide : c'est ce qui garde la force en saison. Effort 7-8 sur 10. **Semaine 8 allégée**. Vacances de la Toussaint : si ton championnat s'arrête 2 semaines, la semaine 8 devient une semaine de **repos complet** et la semaine 9 une semaine de **travail** avec les 3 séances de la trêve (fin du document), puis tu reprends au bloc suivant." },
      { id: "niveau", title: "Semaines 9 à 12 · Garder le niveau", texte: "Le contraste lourd puis rapide et des sprints courts entretiennent la vitesse quand la fatigue de la saison s'installe. Effort 7-8 sur 10. **Semaine 12 allégée**." },
      { id: "treve", title: "Semaines 13 à 16 · Avant la trêve", texte: "Moins de volume pour rester frais sur les derniers matchs de l'année. Effort 7 sur 10. **Semaine 16 allégée**." },
    ],
    treve: { title: "Semaines 17 et 18 · La trêve de Noël", texte: "**Semaine 17 : repos complet**, sans séance. Le corps et la tête en ont besoin. Marche, vélo ou autre sport pour le plaisir si tu en as envie. **Semaine 18 : semaine de travail** pour préparer la reprise de janvier : les 3 séances ci-dessous, sans matériel, sur 3 jours non consécutifs. La veille de la reprise, rien de plus qu'un footing tranquille." },
    guide: [
      { h2: "Avant de commencer" },
      { p: "Pendant la saison, ton club s'occupe déjà d'une grande partie de ta charge d'entraînement. Le but de ce programme n'est pas d'en rajouter, mais d'**entretenir et de faire progresser** ce que tu as construit : sans travail complémentaire, la force et l'explosivité baissent au fil des semaines de compétition. Une seule séance de force par semaine suffit à garder les progrès de l'été pendant 12 semaines, alors qu'une séance toutes les deux semaines ne suffit pas (Rønnestad et al., 2011) : ne saute donc jamais la séance 1 deux semaines de suite." },
      { p: "Tu n'as pas fait de pré-saison ? Fais les semaines 1 et 2 au niveau en dessous du tien, le temps que le corps se réhabitue." },
      ...documents("l'échauffement, ton ou tes objectifs, le gainage et le retour au calme"),
      ...materiel,
      ...niveaux,
      { h2: "Ta semaine autour du match" },
      { p: "Tes 2 séances se placent **loin du match** : la séance 1 (la plus exigeante) au moins 3 jours avant, la séance 2 (plus légère) au plus tard 2 jours avant. Jamais la veille d'un match." },
      { h3: "Match le samedi" },
      { table: { head: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"], rows: [["Repos", "Séance 1", "Club", "Séance 2", "Club", "Repos ou club léger", "MATCH"]] } },
      { h3: "Match le dimanche" },
      { table: { head: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"], rows: [["Repos", "Séance 1", "Club", "Séance 2", "Club", "Repos", "MATCH"]] } },
      { ul: ["La séance 1 peut se faire le même jour qu'un entraînement de club, idéalement le matin ou en fin de séance, si tu te sens bien.", "**Semaine avec deux matchs** : fais seulement la séance 2, en version courte.", "**Grosse fatigue ou petite blessure** : saute la séance, la saison est longue.", "Pas de match ce week-end : fais les deux séances normalement."] },
      { h2: "Comment se déroule une séance" },
      { table: { head: ["Étape", "Durée", "À quoi ça sert"], rows: [
        ["1. Échauffement", "8 min", "Préparer le corps et réduire le risque de blessure : l'équilibre et les réceptions de l'échauffement font partie de la prévention."],
        ["2. Premier bloc", "10-12 min", "Ton premier objectif. Explosivité et Puissance passent toujours en premier."],
        ["3. Deuxième bloc", "10-12 min", "Ton deuxième objectif. Si tu as choisi un seul objectif, ce bloc le travaille sous un autre angle."],
        ["4. Gainage et prévention", "5 min", "Ischios, adducteurs et épaules, très sollicités au handball."],
        ["5. Retour au calme", "3-5 min", "Marche et étirements légers."],
      ] } },
      { note: "Ce que disent les études : une routine d'échauffement avec équilibre et réceptions a presque divisé par deux les blessures du genou et de la cheville chez de jeunes handballeurs (Olsen et al., BMJ, 2005). Le gainage Copenhague a réduit de 41 % les problèmes d'adducteurs (Harøy et al., BJSM, 2019). Un programme de prévention de l'épaule fait 3 fois par semaine les a réduits de 28 % (Andersson et al., BJSM, 2017)." },
      { h3: "La routine épaules (facultative)" },
      { p: "Pour atteindre 3 fois par semaine, ajoute la **routine épaules de 10 minutes** (dans tes séances, après la séance 2) un troisième jour : par exemple avant l'entraînement du club, à la fin de ton échauffement." },
      { h2: "Les 18 semaines" },
      { table: { head: ["Semaines", "Bloc", "Ce qu'on cherche", "Effort"], rows: [
        ["1 à 3, 4 allégée", "Entrer dans la saison", "Garder la force de l'été pendant que les matchs reprennent", "6-7"],
        ["5 à 7, 8 allégée", "Entretenir en intensité", "Peu de séries, lourd et rapide", "7-8"],
        ["9 à 11, 12 allégée", "Garder le niveau", "Contraste lourd puis rapide, sprints courts", "7-8"],
        ["13 à 15, 16 allégée", "Avant la trêve", "Fraîcheur pour les derniers matchs", "7"],
        ["17", "Trêve", "Repos complet", "-"],
        ["18", "Trêve", "3 séances courtes pour préparer la reprise", "6-7"],
      ] } },
      { p: "Les semaines allégées : une série en moins sur chaque exercice. Les séances changent à chaque bloc : tu les trouves dans l'ordre dans le document « Tes séances »." },
      { h3: "Les trêves : une semaine de repos, une semaine de travail" },
      { p: "Sur une trêve de 2 semaines, la **première semaine est une vraie semaine de repos**, et la **deuxième une semaine de travail** pour arriver prêt à la reprise. C'est le cas à Noël (semaines 17 et 18), et à la Toussaint si ton championnat s'arrête (semaines 8 et 9 : la semaine 8 en repos, la semaine 9 avec les 3 séances de la trêve)." },
      { note: "**Règle d'or en saison** : en cas de doute entre faire plus ou faire moins, fais moins. Arriver en forme au match compte plus que la séance." },
      { h2: "Suivre tes séances" },
      { table: { head: ["Date", "Séance", "Jours avant le match", "Effort ressenti (/10)", "Forme du jour (/5)"], rows: Array.from({ length: 8 }, () => [" ", " ", " ", " ", " "]) } },
      { ul: ["Forme du jour à 1 ou 2 sur 5 : fais seulement le gainage et la mobilité, ou repose-toi.", "Jambes lourdes le jour du match deux semaines de suite : avance la séance 1 d'un jour, ou retire une série."] },
      { h2: "Et après ?" },
      { p: "En janvier, la **2e partie de saison** prend le relais, de la reprise jusqu'aux phases finales de juin, avec les mêmes objectifs : chaque partie prépare la suivante." },
      { p: "Une question sur le programme ? Réponds simplement à l'email qui t'a envoyé ce document." },
    ],
  },
};
