// What every session shares, per formula: warm-up, core and prevention block, cool-down,
// the phases, and the Guide (explanations only, no exercise tables).

const niveaux = [
  { h3: "Choisir ton niveau" },
  { table: { head: ["Niveau", "Pour qui", "Dans les séances"], rows: [
    ["Niveau 1", "Tu débutes : peu ou pas de préparation physique jusqu'ici", "Nombre de séries le plus bas, versions « plus facile »"],
    ["Niveau 2", "Tu as quelques bases : une saison de musculation ou de préparation", "Nombre de séries du milieu"],
    ["Niveau 3", "Tu as de l'expérience : plusieurs saisons d'entraînement régulier", "Nombre de séries le plus haut, versions avancées"],
  ] } },
  { p: "Dans tes séances, « 2-4 × 8 » veut dire 2 séries (niveau 1), 3 séries (niveau 2) ou 4 séries (niveau 3) de 8 répétitions. « 2-3 × 8 » : 2 séries aux niveaux 1 et 2, 3 au niveau 3." },
  { h3: "Régler l'intensité : l'échelle d'effort" },
  { table: { head: ["Note", "Ressenti", "Repère"], rows: [
    ["5-6", "Facile à modéré", "Tu pourrais encore faire 4 à 5 répétitions"],
    ["7-8", "Difficile mais contrôlé", "Il te reste 2 à 3 répétitions en réserve"],
    ["9", "Très difficile", "Plus qu'une répétition possible"],
    ["10", "Maximal", "À éviter dans ce programme"],
  ] } },
  { warn: "Douleur vive, articulation qui lâche, vertige : arrête l'exercice. Une gêne qui dure plus de 48 heures ou qui revient à chaque séance doit être vue par un professionnel de santé." },
];

const documents = (seances) => [
  { table: { head: ["Tu as reçu", "À quoi ça sert"], rows: [
    ["Ce guide", "Comprendre le programme : fonctionnement, planning, progression, règles"],
    ["Tes séances", `Toutes tes séances écrites en entier, dans l'ordre, avec ${seances} et la fiche illustrée de chaque exercice`],
    ["Option course (si choisie)", "Tes séances de course, en plus"],
  ] } },
  { note: "**Le jour de la séance, tu n'as besoin que du document « Tes séances »** : tout y est, de l'échauffement au retour au calme. Ce guide sert à comprendre le programme, lis-le une fois en entier avant de commencer." },
];

const retourAuCalme = "2 minutes de marche, puis des étirements légers de 20 à 30 secondes, sans forcer : fléchisseurs de hanche, quadriceps, ischios, mollets, pectoraux et épaules.";

export const formules = {
  "pre-saison": {
    name: "Pré-saison",
    tag: "Avant la saison",
    color: "#FF5A1F",
    duree: "8 semaines",
    frequence: "3 séances + 1 bonus",
    seance: "45 à 60 min",
    echauffement: { title: "Échauffement · 10 à 12 min", rows: [
      ["footing-dynamique", "3 min", ""], ["fente-rotation", "6 par côté", ""], ["ouverture-hanche", "8 par côté", ""], ["pont-fessier", "2 × 10", "15 s"],
      ["planche", "2 × 20 s", "15 s"], ["equilibre", "2 × 20 s par jambe", ""], ["saut-reception", "2 × 5", "20 s"], ["accelerations", "3 passages", "retour en marchant"],
    ] },
    gainage: {
      A: [["planche", "2-4 × 30 s", "30 s"], ["gainage-lateral", "2-3 × 20 s par côté", "20 s"], ["nordic", "2-3 × 4", "60 s"]],
      B: [["dead-bug", "2-3 × 8 par côté", "30 s"], ["ytw", "2-3 × 8", "30 s"], ["equilibre-balle", "2 × 30 s par jambe", "20 s"]],
      C: [["pont-une-jambe", "2-3 × 10 par jambe", "30 s"], ["copenhague", "2-3 × 15 s par côté", "30 s", "version genou"], ["rotation-externe", "2-3 × 12 par bras", "30 s"]],
    },
    bonus: { title: "Séance D (bonus, facultative) · 20 min", rows: [["planche", "2 × 30 s", "30 s"], ["gainage-lateral", "2 × 20 s par côté", "20 s"], ["nordic", "2 × 3", "60 s"], ["hanches-9090", "1 × 8 par côté", ""], ["cheville-mur", "1 × 10 par côté", ""], ["rotation-thoracique", "1 × 8 par côté", ""]] },
    retourAuCalme,
    phases: [
      { id: "bases", title: "Semaines 1-2 · Bases", texte: "Réhabituer le corps à l'effort et apprendre les gestes. Effort 5-6 sur 10." },
      { id: "force", title: "Semaines 3-5 · Force", texte: "Monter progressivement les charges. La semaine 5 est la plus chargée. Effort 7-8 sur 10." },
      { id: "explo", title: "Semaines 6-7 · Explosivité", texte: "Moins de volume, plus de vitesse : chaque répétition de qualité maximale. Effort 7-8 sur 10." },
    ],
    affutage: { title: "Semaine 8 · Affûtage", texte: "Refais les séances A, B et C des semaines 6-7 en faisant **la moitié des séries**, avec la même intensité. Tu aborderas la reprise avec ton club en pleine forme." },
    guide: [
      { h2: "Avant de commencer" },
      { p: "8 semaines pour reprendre sur des bases solides avant la reprise avec ton club. Ce guide t'explique comment fonctionne ton programme." },
      ...documents("l'échauffement, ton ou tes objectifs, le gainage et le retour au calme"),
      { h3: "Matériel" },
      { p: "Rien d'obligatoire : tout peut se faire au poids du corps. Si tu as accès à une salle ou à un peu de matériel (haltères, élastique, banc), les fiches exercices indiquent des variantes." },
      ...niveaux,
      { h2: "Ta semaine type" },
      { p: "Chaque semaine compte **3 séances (A, B et C)**, plus une **séance D bonus** facultative, courte, centrée sur la prévention et la mobilité." },
      { table: { head: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"], rows: [["Séance A", "Repos ou club", "Séance B", "Repos ou club", "Séance D (bonus)", "Séance C", "Repos"]] } },
      { p: "C'est un exemple : adapte-le à ton emploi du temps en respectant ces règles." },
      { ul: ["Au moins **48 heures** entre deux séances A, B ou C.", "Au moins **un jour de repos complet** par semaine.", "Pas de séance la veille d'un match amical ou d'un entraînement collectif très intense.", "Une séance ratée ne se rattrape pas en doublant : reprends simplement à la séance suivante."] },
      { h2: "Comment se déroule une séance" },
      { table: { head: ["Étape", "Durée", "À quoi ça sert"], rows: [
        ["1. Échauffement", "10-12 min", "Préparer le corps et réduire le risque de blessure. Le même à chaque séance."],
        ["2. Premier bloc", "15-20 min", "Ton premier objectif. Explosivité et Puissance passent toujours en premier, quand tu as toute ton énergie."],
        ["3. Deuxième bloc", "15-20 min", "Ton deuxième objectif. Si tu as choisi un seul objectif, ce bloc le travaille sous un autre angle."],
        ["4. Gainage et prévention", "5-8 min", "Renforcer les zones les plus exposées au handball : genoux, chevilles, épaules, ischios, adducteurs."],
        ["5. Retour au calme", "5 min", "Marche et étirements légers."],
      ] } },
      { note: "**Pourquoi un échauffement si complet ?** Une grande étude menée dans 120 clubs de handball norvégiens a montré qu'un échauffement travaillant la course, l'équilibre et la réception des sauts divisait environ par deux les blessures du genou et de la cheville (Olsen et al., BMJ, 2005)." },
      { h2: "La progression sur 8 semaines" },
      { table: { head: ["Semaine", "Phase", "Ce qu'on cherche", "Volume", "Effort"], rows: [
        ["1", "Bases", "Réhabituer le corps à l'effort, apprendre les gestes", "Faible", "5-6"],
        ["2", "Bases", "Idem, un peu plus de travail", "Faible à moyen", "6"],
        ["3", "Force", "Monter progressivement les charges", "Moyen", "7"],
        ["4", "Force", "Continuer la montée", "Moyen à élevé", "7-8"],
        ["5", "Force", "Semaine la plus chargée", "Élevé", "8"],
        ["6", "Explosivité", "Moins de volume, plus de vitesse", "Moyen", "7-8"],
        ["7", "Explosivité", "Qualité maximale de chaque répétition", "Moyen", "8"],
        ["8", "Affûtage", "Récupérer en gardant l'intensité", "Réduit de moitié", "6-7"],
      ] } },
      { note: "**Semaine 8 : moins, c'est mieux.** Tu fais la moitié des séries, avec la même qualité, pour aborder la reprise en pleine forme." },
      { h2: "Suivre tes séances" },
      { p: "Note chaque séance : c'est le meilleur moyen de progresser et de repérer la fatigue." },
      { table: { head: ["Date", "Séance", "Effort ressenti (/10)", "Forme du jour (/5)", "Gênes ou remarques"], rows: Array.from({ length: 8 }, () => [" ", " ", " ", " ", " "]) } },
      { ul: ["Forme du jour à 1 ou 2 sur 5 deux séances de suite : allège (moins de séries) ou prends un jour de repos en plus.", "Tout est facile (effort à 5 alors que 7-8 est prévu) : prends le niveau au-dessus."] },
      { h2: "Et après ?" },
      { p: "À la fin des 8 semaines, la saison commence. Pour garder ce que tu as construit sans fatiguer tes jambes avant les matchs, tu peux enchaîner avec la formule **Maintien en saison** : 2 séances courtes par semaine." },
      { p: "Une question sur le programme ? Réponds simplement à l'email qui t'a envoyé ce document." },
    ],
  },

  "maintien-saison": {
    name: "Maintien en saison",
    tag: "Pendant la saison",
    color: "#00C2B2",
    duree: "12 semaines",
    frequence: "2 séances par semaine",
    seance: "30 à 40 min",
    echauffement: { title: "Échauffement · 8 min", rows: [
      ["footing-dynamique", "2 min", ""], ["fente-rotation", "5 par côté", ""], ["pont-fessier", "1 × 10", ""], ["planche", "1 × 20 s", ""],
      ["equilibre", "20 s par jambe", ""], ["saut-reception", "1 × 5", ""], ["accelerations", "2 passages", "retour en marchant", "70 %, puis 85 %"],
    ] },
    gainage: {
      "1": [["nordic", "2 × 3-5", "60 s"], ["copenhague", "2 × 15 s par côté", "30 s", "version genou"], ["planche", "1-2 × 30 s", "30 s"]],
      "2": [["rotation-externe", "2 × 12 par bras", "30 s"], ["ytw", "2 × 8", "30 s"], ["equilibre-balle", "2 × 20 s par jambe", "20 s"]],
    },
    retourAuCalme,
    blocs: "Les séances sont les mêmes pendant les 12 semaines. Les **semaines 4, 8 et 12 sont allégées** : fais une série en moins sur chaque exercice. Semaines 1 à 3, 5 à 7 et 9 à 11 : séances comme indiqué, en visant un effort de 7-8 sur 10.",
    guide: [
      { h2: "Avant de commencer" },
      { p: "Pendant la saison, ton club s'occupe déjà d'une grande partie de ta charge d'entraînement. Le but de ce programme n'est pas d'en rajouter, mais d'**entretenir** ce que tu as construit : sans travail complémentaire, la force et l'explosivité baissent au fil des semaines de compétition." },
      ...documents("l'échauffement, ton ou tes objectifs, le gainage et le retour au calme"),
      { h3: "Matériel" },
      { p: "Rien d'obligatoire : tout peut se faire au poids du corps. Les fiches exercices indiquent des variantes si tu as accès à une salle ou à un peu de matériel." },
      ...niveaux,
      { h2: "Ta semaine autour du match" },
      { p: "Tes 2 séances se placent **loin du match** : la séance 1 (la plus exigeante) au moins 3 jours avant, la séance 2 (plus légère) au plus tard 2 jours avant. Jamais la veille d'un match." },
      { h3: "Match le samedi" },
      { table: { head: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"], rows: [["Repos", "Séance 1", "Club", "Séance 2", "Club", "Repos ou club léger", "MATCH"]] } },
      { h3: "Match le dimanche" },
      { table: { head: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"], rows: [["Repos", "Séance 1", "Club", "Séance 2", "Club", "Repos", "MATCH"]] } },
      { ul: ["La séance 1 peut se faire le même jour qu'un entraînement de club, idéalement le matin ou en fin de séance, si tu te sens bien.", "**Semaine avec deux matchs** : fais seulement la séance 2, en version courte.", "**Grosse fatigue ou petite blessure** : saute la séance, la saison est longue.", "Pas de match ce week-end : fais les deux séances normalement."] },
      { h2: "Comment se déroule une séance" },
      { table: { head: ["Étape", "Durée", "À quoi ça sert"], rows: [
        ["1. Échauffement", "8 min", "Préparer le corps et réduire le risque de blessure."],
        ["2. Premier bloc", "10-12 min", "Ton premier objectif. Explosivité et Puissance passent toujours en premier."],
        ["3. Deuxième bloc", "10-12 min", "Ton deuxième objectif. Si tu as choisi un seul objectif, ce bloc le travaille sous un autre angle."],
        ["4. Gainage et prévention", "5 min", "Épaules, ischios et adducteurs, très sollicités au handball."],
        ["5. Retour au calme", "3-5 min", "Marche et étirements légers."],
      ] } },
      { note: "Une étude sur 660 joueurs et joueuses de haut niveau a montré qu'un programme de prévention de l'épaule fait 3 fois par semaine réduisait les problèmes d'épaule de 28 % (Andersson et al., BJSM, 2017). C'est pour cela que chaque séance se termine par un bloc de prévention." },
      { h2: "La progression sur 12 semaines" },
      { table: { head: ["Semaines", "Bloc", "Ce qu'on cherche", "Volume", "Effort"], rows: [
        ["1 à 3", "Bloc 1", "Installer la routine, reprendre les gestes", "Normal", "7"],
        ["4", "Allégée", "Récupérer", "Une série en moins", "6"],
        ["5 à 7", "Bloc 2", "Entretenir, un peu plus d'intensité", "Normal", "7-8"],
        ["8", "Allégée", "Récupérer", "Une série en moins", "6"],
        ["9 à 11", "Bloc 3", "Garder le niveau", "Normal", "7-8"],
        ["12", "Allégée", "Récupérer avant le cycle suivant", "Une série en moins", "6"],
      ] } },
      { note: "**Règle d'or en saison** : en cas de doute entre faire plus ou faire moins, fais moins. Arriver en forme au match compte plus que la séance." },
      { h2: "Suivre tes séances" },
      { table: { head: ["Date", "Séance", "Jours avant le match", "Effort ressenti (/10)", "Forme du jour (/5)"], rows: Array.from({ length: 8 }, () => [" ", " ", " ", " ", " "]) } },
      { ul: ["Forme du jour à 1 ou 2 sur 5 : fais seulement le gainage et la mobilité, ou repose-toi.", "Jambes lourdes le jour du match deux semaines de suite : avance la séance 1 d'un jour, ou retire une série."] },
      { h2: "Et après ?" },
      { p: "Le programme est conçu pour être reconduit : à la fin des 12 semaines, recommence en prenant le niveau au-dessus si tout t'a semblé facile. Pendant la trêve, la formule **Pré-saison** permet de repartir sur de nouvelles bases." },
      { p: "Une question sur le programme ? Réponds simplement à l'email qui t'a envoyé ce document." },
    ],
  },
};
