// Goal sheet: Développement musculaire (force, prise de masse, gainage / stabilité).
export default {
  title: "Développement musculaire",
  tag: "Fiche objectif",
  color: "#FF5A1F",
  subtitle: "Gagner en force et en muscle pour être plus solide dans les duels et plus stable sur tes appuis.",
  meta: [["Travaille", "Force · Masse · Gainage"], ["Formules", "Pré-saison et Maintien"], ["Bloc", "15 à 20 min"]],
  blocks: [
    { h2: "Ce que tu vas travailler" },
    { p: "Au handball, on encaisse des contacts à chaque attaque et à chaque défense. Des muscles plus forts protègent tes articulations et te rendent plus difficile à déséquilibrer. Cette fiche développe trois qualités :" },
    { ul: [
      "**Force** : pousser, tirer et soulever plus lourd.",
      "**Prise de masse** : développer le volume musculaire.",
      "**Gainage et stabilité** : transmettre la force des jambes au bras et rester stable dans les contacts.",
    ] },
    { h3: "Les règles d'or" },
    { ul: [
      "**La technique d'abord** : une charge n'augmente que si le mouvement reste propre sur toutes les répétitions.",
      "**Progresser un peu chaque semaine** : une répétition de plus, ou une charge un peu plus lourde.",
      "**Contrôler la descente** : 2 à 3 secondes pour descendre, puis remonter avec énergie.",
      "Garde 2 à 3 répétitions en réserve (effort 7-8 sur 10). Pas d'échec musculaire.",
    ] },
    { note: "**Prise de masse** : l'entraînement donne le signal, mais les muscles se construisent avec l'alimentation et le sommeil. Mange suffisamment, avec des protéines à chaque repas, et dors 8 heures. Nos programmes ne comprennent pas de plan alimentaire : pour un suivi, adresse-toi à un ou une diététicienne." },
    { h3: "Au poids du corps ou en salle ?" },
    { p: "Chaque exercice a une version **sans matériel** et une version **avec charge**. Sans matériel, rends l'exercice plus dur en ralentissant la descente, en ajoutant un sac à dos lesté ou en passant à la variante sur une jambe." },

    { pagebreak: true },
    { h2: "Les exercices" },
    { exercise: "Squat", how: "Pieds largeur d'épaules, descends comme pour t'asseoir, cuisses au moins parallèles au sol, puis remonte. Avec charge : un haltère tenu contre la poitrine (goblet squat) ou une barre.", cues: "Dos droit, talons au sol, genoux dans l'axe des pieds.", easier: "Descendre sur une chaise et se relever." },
    { exercise: "Fente arrière", how: "Recule une jambe et descends jusqu'à ce que le genou arrière frôle le sol. Reviens en poussant sur la jambe avant. Avec charge : un haltère dans chaque main.", cues: "Buste droit, genou avant au-dessus de la cheville.", easier: "En s'aidant d'un appui (mur, chaise)." },
    { exercise: "Squat bulgare", how: "Pied arrière posé sur un banc ou une chaise, descends sur la jambe avant puis remonte.", cues: "C'est la jambe avant qui travaille, le pied arrière sert seulement d'équilibre." },
    { exercise: "Soulevé de terre jambes tendues (roumain)", how: "Debout, genoux légèrement fléchis, penche le buste vers l'avant en reculant les fesses, dos plat, jusqu'à sentir l'étirement des ischios, puis redresse-toi. Avec charge : haltères ou barre.", cues: "Dos plat du début à la fin, la charge glisse le long des jambes.", easier: "Sans charge, sur une jambe avec un appui." },
    { exercise: "Hip thrust", how: "Haut du dos appuyé sur un banc ou un canapé, pieds au sol, monte le bassin jusqu'à l'alignement épaules-hanches-genoux. Avec charge : haltère ou barre sur les hanches.", cues: "Serre les fessiers en haut une seconde.", easier: "Pont fessier au sol." },
    { exercise: "Pompes", how: "Mains un peu plus larges que les épaules, corps gainé, descends la poitrine près du sol puis pousse. Avec charge : développé couché aux haltères ou à la barre.", cues: "Coudes à 45° du corps, le bassin ne s'affaisse pas.", easier: "Mains surélevées (table, banc) ou genoux au sol." },
    { exercise: "Rowing", how: "Buste penché, dos plat, tire un haltère (ou un sac lesté) vers la hanche. Sans matériel : rowing inversé sous une table solide.", cues: "Tire avec le dos, omoplate qui se rapproche de la colonne.", easier: "Rowing inversé les pieds plus près." },
    { exercise: "Développé militaire", how: "Debout ou en position assise, pousse les haltères au-dessus de la tête, bras tendus, puis redescends aux épaules.", cues: "Gainage serré, ne cambre pas le bas du dos.", easier: "Pompes en V (fesses en l'air, tête vers le sol)." },
    { exercise: "Tractions", how: "En suspension à une barre, tire jusqu'à passer le menton au-dessus.", cues: "Descente contrôlée, bras presque tendus en bas.", easier: "Tractions avec élastique, ou descente lente seulement (sauter en haut, descendre en 4 s)." },
    { exercise: "Pallof press", how: "Élastique attaché sur le côté à hauteur de poitrine, tiens-le à deux mains contre le sternum et tends les bras devant toi sans laisser le buste tourner.", cues: "Résiste à la rotation : c'est un exercice de gainage." },
    { exercise: "Marche du fermier", how: "Marche 20 mètres avec une charge lourde dans chaque main (haltères, sacs, bidons).", cues: "Épaules basses, buste droit, pas réguliers." },
    { exercise: "Planche et gainage latéral", how: "Sur les avant-bras, corps aligné de la tête aux talons. Sur le côté pour le gainage latéral.", cues: "Serre les fessiers et le ventre, respire normalement.", easier: "Genoux au sol." },

    { pagebreak: true },
    { h2: "Pré-saison : tes séances" },
    { p: "« 2-4 × 10 » : 2 séries au niveau 1, 3 au niveau 2, 4 au niveau 3. Choisis une charge qui te laisse 2 à 3 répétitions en réserve." },
    { h3: "Semaines 1-2 · Bases" },
    { p: "Charges légères, apprentissage des gestes, effort 6 sur 10." },
    { session: "Séance A", rows: [["Squat", "2-3 × 10", "75 s"], ["Pompes", "2-3 × 10", "60 s"], ["Planche", "2 × 30 s", "30 s"]] },
    { session: "Séance B", rows: [["Soulevé de terre jambes tendues", "2-3 × 10", "75 s"], ["Rowing", "2-3 × 10", "60 s"], ["Pallof press", "2 × 10 par côté", "30 s"]] },
    { session: "Séance C", rows: [["Fente arrière", "2-3 × 8 par jambe", "60 s"], ["Développé militaire", "2-3 × 10", "60 s"], ["Gainage latéral", "2 × 20 s par côté", "30 s"]] },
    { h3: "Semaines 3-5 · Force" },
    { p: "La phase clé de cette fiche. Monte les charges chaque semaine, effort 7-8 sur 10." },
    { session: "Séance A", rows: [["Squat", "3-4 × 6-8", "2 min"], ["Pompes (ou développé couché)", "3-4 × 8", "90 s"], ["Marche du fermier", "3 × 20 m", "60 s"]] },
    { session: "Séance B", rows: [["Hip thrust", "3-4 × 8", "90 s"], ["Tractions (ou rowing)", "3-4 × 6-8", "90 s"], ["Pallof press", "3 × 10 par côté", "30 s"]] },
    { session: "Séance C", rows: [["Squat bulgare", "3 × 8 par jambe", "90 s"], ["Soulevé de terre jambes tendues", "3 × 8", "90 s"], ["Développé militaire", "3 × 8", "75 s"]] },
    { note: "**Si ton objectif est la prise de masse** : sur les semaines 3 à 7, fais 8 à 12 répétitions au lieu de 6 à 8, avec 60 à 90 secondes de repos, et ajoute une série sur le premier exercice de chaque séance." },
    { h3: "Semaines 6-7 · Explosivité" },
    { p: "Le volume baisse pour laisser de l'énergie aux qualités explosives. On garde des charges lourdes, avec moins de séries." },
    { session: "Séance A", rows: [["Squat", "3 × 5", "2 min"], ["Pompes", "3 × 8", "75 s"]] },
    { session: "Séance B", rows: [["Hip thrust", "3 × 6", "90 s"], ["Tractions (ou rowing)", "3 × 6", "90 s"]] },
    { session: "Séance C", rows: [["Fente arrière", "3 × 6 par jambe", "90 s"], ["Pallof press", "2 × 10 par côté", "30 s"]] },
    { h3: "Semaine 8 · Affûtage" },
    { p: "Reprends les séances des semaines 6-7 en faisant **la moitié des séries**, avec les mêmes charges." },

    { h2: "Maintien en saison : tes séances" },
    { p: "Deux séances courtes par semaine suffisent pour garder ta force. On garde des charges assez lourdes, mais avec peu de séries." },
    { session: "Séance 1 · Force (loin du match)", rows: [["Squat ou squat bulgare", "2-3 × 5-6", "2 min"], ["Rowing ou tractions", "2-3 × 6", "90 s"], ["Hip thrust", "2 × 8", "75 s"]] },
    { session: "Séance 2 · Gainage et stabilité", rows: [["Pompes", "2 × 8-10", "60 s"], ["Pallof press", "2 × 10 par côté", "30 s"], ["Marche du fermier", "2 × 20 m", "60 s"]] },
    { table: { head: ["Semaines", "Ajustement"], rows: [
      ["1 à 3, 5 à 7, 9 à 11", "Séances comme indiqué"],
      ["4, 8 et 12", "Semaine allégée : une série en moins partout"],
    ] } },
    { note: "**Placement dans la semaine** : la séance 1 au moins 3 jours avant le match. La séance 2 peut se faire jusqu'à 2 jours avant." },
  ],
};
