export type Block = { h: string } | { p: string } | { ul: string[] };
// A study post summarises one published paper in our own words and links to the original.
export type Source = { cite: string; url: string; access: string };
// theme: used for the filters and the colour; exos: exercises shown as animations in the article
// (the first one also illustrates the card).
export type Theme = "prevention" | "reprise" | "saison" | "performance";
export const themes: Record<Theme, string> = { prevention: "Prévention", reprise: "Reprise", saison: "En saison", performance: "Performance" };
export type Post = { slug: string; title: string; desc: string; date: string; body: Block[]; source?: Source; theme: Theme; exos: string[] };

export const posts: Post[] = [
  {
    slug: "etude-echauffement-blessures-genou-cheville",
    theme: "prevention",
    exos: ["saut-reception", "equilibre", "freinage"],
    title: "Étude : un échauffement structuré divise par deux les blessures du genou et de la cheville",
    desc: "Une étude menée dans 120 clubs de handball norvégiens montre qu'un échauffement ciblé réduit fortement les blessures aux membres inférieurs.",
    date: "2026-09-23",
    source: {
      cite: "Olsen O-E, Myklebust G, Engebretsen L, Holme I, Bahr R. Exercises to prevent lower limb injuries in youth sports: cluster randomised controlled trial. BMJ. 2005;330(7489):449.",
      url: "https://doi.org/10.1136/bmj.38330.632801.8F",
      access: "Article en libre accès sur le site du BMJ.",
    },
    body: [
      { p: "Les entorses de la cheville et les blessures du genou, notamment du ligament croisé, font partie des blessures les plus fréquentes au handball. Une équipe du centre de recherche sur les traumatismes sportifs d'Oslo a voulu savoir si un simple échauffement pouvait les éviter." },
      { h: "Ce que les chercheurs ont fait" },
      { p: "L'étude a suivi 1 837 jeunes de 15 à 17 ans, licenciés dans 120 clubs de handball en Norvège, pendant une saison entière (8 mois). La moitié des clubs a remplacé son échauffement habituel par un programme structuré. L'autre moitié a continué comme avant, pour servir de comparaison." },
      { p: "Le programme se faisait en début d'entraînement et combinait :" },
      { ul: ["des exercices de course et de changements de direction", "des exercices d'équilibre, sur tapis ou plateau instable", "un travail sur la réception des sauts, genoux dans l'axe", "du renforcement des jambes et des exercices d'explosivité"] },
      { h: "Les résultats" },
      { p: "Dans les clubs qui ont suivi le programme, les blessures aiguës du genou et de la cheville ont été environ deux fois moins nombreuses que dans les autres clubs. Selon les auteurs, un échauffement qui apprend à mieux contrôler le genou et la cheville lors des réceptions et des pivots pourrait diviser par deux ces blessures chez les jeunes sportifs et sportives." },
      { h: "Ce qu'on en retient" },
      { ul: ["L'échauffement n'est pas une formalité : c'est le meilleur moment pour prévenir les blessures.", "Quelques exercices d'équilibre et de réception, répétés à chaque séance, suffisent à faire la différence.", "C'est pour cela que nos programmes intègrent un travail d'appuis et de réception dès les premières semaines."] },
    ],
  },
  {
    slug: "etude-prevention-epaule-handball",
    theme: "prevention",
    exos: ["rotation-externe-haute", "rotation-externe", "ytw", "rotation-thoracique"],
    title: "Étude : 3 séances d'exercices par semaine pour protéger l'épaule des handballeurs et handballeuses",
    desc: "Un programme de prévention testé sur 660 joueurs et joueuses de haut niveau réduit les problèmes d'épaule de 28 %.",
    date: "2026-09-23",
    source: {
      cite: "Andersson SH, Bahr R, Clarsen B, Myklebust G. Preventing overuse shoulder injuries among throwing athletes: a cluster-randomised controlled trial in 660 elite handball players. British Journal of Sports Medicine. 2017;51(14):1073-1080.",
      url: "https://doi.org/10.1136/bjsports-2016-096226",
      access: "Article en accès gratuit, également disponible sur le site du centre de recherche OSTRC.",
    },
    body: [
      { p: "Au handball, on arme et on tire des centaines de fois par semaine. Résultat : les douleurs d'épaule dues à la répétition des tirs sont très courantes, y compris chez les meilleurs. Une étude norvégienne a testé un programme d'exercices pour les prévenir." },
      { h: "Ce que les chercheurs ont fait" },
      { p: "660 joueurs et joueuses de première division, répartis dans 45 équipes (22 équipes féminines et 23 masculines), ont été suivis pendant une saison de 7 mois. La moitié des équipes a ajouté à son échauffement un programme de prévention de l'épaule, 3 fois par semaine. Les autres équipes ont gardé leur échauffement habituel." },
      { p: "Le programme visait à :" },
      { ul: ["améliorer la rotation interne de l'épaule", "renforcer les muscles qui font tourner l'épaule vers l'extérieur", "renforcer les muscles de l'omoplate", "travailler la mobilité du haut du dos et l'enchaînement des mouvements des jambes jusqu'au bras"] },
      { h: "Les résultats" },
      { p: "Dans les équipes qui ont suivi le programme, le risque d'avoir des problèmes d'épaule pendant la saison était 28 % plus faible. Les auteurs recommandent donc d'intégrer ce type d'exercices à l'échauffement." },
      { h: "Ce qu'on en retient" },
      { ul: ["Quelques minutes, trois fois par semaine, suffisent.", "Le travail avec un élastique et le renforcement de l'omoplate sont au cœur de la prévention.", "Pour démarrer, tu peux t'appuyer sur notre article : 4 exercices simples pour protéger les épaules."] },
    ],
  },
  {
    slug: "etude-exigences-physiques-handball",
    theme: "performance",
    exos: ["squat-jump", "navette-5105", "departs-10"],
    title: "Étude : ce que le handball demande vraiment au corps",
    desc: "Une revue scientifique fait le point sur les qualités physiques et mentales qui font la performance au handball.",
    date: "2026-09-23",
    source: {
      cite: "Wagner H, Finkenzeller T, Würth S, von Duvillard SP. Individual and team performance in team-handball: a review. Journal of Sports Science and Medicine. 2014;13(4):808-816.",
      url: "https://www.jssm.org/volume13/iss4/cap/jssm-13-808.pdf",
      access: "Article en libre accès sur le site du Journal of Sports Science and Medicine.",
    },
    body: [
      { p: "Pour bien se préparer, il faut savoir à quoi on se prépare. Des chercheurs des universités de Salzbourg (Autriche) et du Delaware (États-Unis) ont rassemblé les études disponibles pour décrire ce qui fait la performance au handball." },
      { h: "Un sport d'efforts courts et répétés" },
      { p: "Pendant un match, chaque personne sur le terrain parcourt en moyenne environ 4 km, entre 2 et 5 km selon le poste. Mais ce n'est pas la distance qui compte le plus : c'est l'alternance constante entre marche, course, sprints, sauts, changements de direction et contacts avec l'adversaire." },
      { h: "Les qualités qui font la différence" },
      { p: "La revue identifie plusieurs familles de qualités, qui se combinent :" },
      { ul: ["l'endurance, pour répéter les efforts intenses jusqu'à la fin du match", "la force et la puissance, pour les duels, les sauts et la vitesse de tir", "la vitesse et l'agilité, pour les démarrages et les changements de direction", "la coordination et la technique", "les qualités mentales et la lecture du jeu"] },
      { h: "Ce qu'on en retient" },
      { ul: ["Courir longtemps à allure régulière ne suffit pas : il faut s'entraîner à répéter des efforts courts et intenses.", "La force et l'explosivité sont aussi importantes que le cardio.", "C'est pour cela que nos programmes peuvent combiner deux objectifs, par exemple développement musculaire et explosivité, ou condition physique et puissance."] },
    ],
  },
  {
    slug: "reprise-preparation-physique-handball",
    theme: "reprise",
    exos: ["fente-arriere", "squat", "planche"],
    title: "Bien reprendre la préparation physique au handball après l'été",
    desc: "Comment reprendre progressivement après la coupure estivale et arriver en forme au premier entraînement collectif.",
    date: "2026-09-21",
    body: [
      { p: "Après plusieurs semaines sans handball, le corps a perdu un peu de forme, et la tentation est grande de tout reprendre à pleine intensité dès la première semaine. C'est souvent là que les petites blessures arrivent. Une reprise progressive vaut mieux qu'un départ trop rapide." },
      { h: "Commence par le général" },
      { p: "Pendant les deux premières semaines, l'objectif est de réhabituer le corps à l'effort : footing léger ou vélo, gainage, squats et fentes au poids du corps, et de la mobilité pour les épaules, les hanches et les chevilles. Deux à trois séances courtes suffisent." },
      { h: "Monte l'intensité par paliers" },
      { p: "Ensuite, ajoute progressivement de la force (charges légères puis plus lourdes), des sauts et des accélérations courtes. Le handball est un sport de sprints, de sauts et de changements de direction : ton travail doit s'en rapprocher au fil des semaines." },
      { h: "Trois erreurs à éviter" },
      { ul: ["Enchaîner des séances intenses sans jour de récupération.", "Négliger l'échauffement, surtout pour les épaules et les chevilles.", "Vouloir rattraper en une semaine ce qui a été perdu en un mois."] },
      { p: "Une préparation de plusieurs semaines, structurée en phases, te laisse le temps de progresser sans forcer. C'est le principe de la formule Pré-saison de 6M Lab." },
    ],
  },
  {
    slug: "epaules-handball-4-exercices-prevention",
    theme: "prevention",
    exos: ["rotation-externe", "pompes-scapulaires", "gainage-lateral"],
    title: "Handball : 4 exercices simples pour protéger tes épaules",
    desc: "Quatre exercices avec élastique et poids du corps à intégrer à ton échauffement pour préparer les épaules aux tirs répétés.",
    date: "2026-09-21",
    body: [
      { p: "Les tirs répétés sollicitent fortement l'épaule. Renforcer les muscles qui la stabilisent fait partie d'une bonne préparation. Voici quatre exercices simples, à faire avec un élastique de résistance légère ou au poids du corps." },
      { h: "1. Rotation externe avec élastique" },
      { p: "Coude collé au corps et plié à 90°, tire l'élastique vers l'extérieur sans bouger le buste, puis reviens lentement. 2 séries de 12 à 15 répétitions par bras." },
      { h: "2. Écarté d'élastique" },
      { p: "Bras tendus devant toi, écarte l'élastique en rapprochant les omoplates. 2 séries de 12 à 15 répétitions." },
      { h: "3. Pompes scapulaires" },
      { p: "En position de pompe, bras tendus, rapproche puis écarte les omoplates sans plier les coudes. 2 séries de 10 répétitions." },
      { h: "4. Gainage latéral" },
      { p: "Appui sur l'avant-bras, corps aligné, tiens 20 à 30 secondes de chaque côté, 2 à 3 fois." },
      { h: "Comment les intégrer" },
      { p: "Fais-les 2 à 3 fois par semaine, dans ton échauffement ou avant les séances de tirs, avec une charge légère et un mouvement lent et contrôlé." },
      { p: "Ces conseils sont généraux et ne remplacent pas l'avis d'un professionnel de santé. En cas de douleur à l'épaule, arrête-toi et consulte." },
    ],
  },
  {
    slug: "garder-la-forme-en-saison-handball",
    theme: "saison",
    exos: ["pogos", "squat"],
    title: "Comment garder la forme en pleine saison de handball",
    desc: "Deux séances courtes par semaine pour conserver ta force et ta vivacité sans te fatiguer avant les matchs.",
    date: "2026-09-21",
    body: [
      { p: "Entre les entraînements de club et les matchs, la préparation physique passe souvent à la trappe. Pourtant, la condition acquise en pré-saison peut s'estomper si elle n'est plus entretenue." },
      { h: "Peu, mais régulier" },
      { p: "Deux séances de 30 à 40 minutes par semaine suffisent pour entretenir la force et l'explosivité, à condition de les faire régulièrement." },
      { h: "Place-les intelligemment" },
      { ul: ["Évite les séances éprouvantes la veille d'un match.", "Place-les après les jours les plus chargés du club, pas avant.", "Garde une séance plus dynamique (sauts, accélérations) et une plus axée sur la force."] },
      { h: "Écoute ta fatigue" },
      { p: "Si tu es plus fatigué que d'habitude, réduis le volume plutôt que de supprimer la séance. Un peu de mobilité et de gainage valent mieux que rien." },
      { p: "C'est le principe de la 1re partie de saison de 6M Lab : de septembre à Noël, 2 séances courtes par semaine, pensées pour ne pas te fatiguer avant les matchs." },
    ],
  },
  // ---- Scheduled: 2 articles a month, published on their date (isLive) ----
  {
    slug: "etude-sommeil-blessures-jeunes-sportifs",
    theme: "prevention",
    exos: ["hanches-9090", "ouverture-hanche"],
    title: "Étude : moins de 8 heures de sommeil, plus de blessures chez les jeunes sportifs",
    desc: "Une étude américaine sur 112 jeunes athlètes montre que ceux qui dorment moins de 8 heures se blessent nettement plus souvent.",
    date: "2026-10-05",
    source: {
      cite: "Milewski MD, Skaggs DL, Bishop GA, Pace JL, Ibrahim DA, Wren TAL, Barzdukas A. Chronic lack of sleep is associated with increased sports injuries in adolescent athletes. Journal of Pediatric Orthopaedics. 2014;34(2):129-133.",
      url: "https://pubmed.ncbi.nlm.nih.gov/?term=%22Chronic+lack+of+sleep+is+associated+with+increased+sports+injuries+in+adolescent+athletes%22",
      access: "Résumé en libre accès sur PubMed, la base publique des études médicales.",
    },
    body: [
      { p: "Entraînements le soir, cours le lendemain, téléphone avant de dormir : chez les jeunes joueurs et joueuses, le sommeil passe souvent en dernier. Une équipe de chercheurs de Los Angeles a voulu savoir si cela change quelque chose au risque de blessure." },
      { h: "Ce que les chercheurs ont fait" },
      { p: "112 jeunes sportifs et sportives de collège et de lycée ont répondu à un questionnaire sur leurs habitudes : heures de sommeil, heures d'entraînement, cours particuliers, plaisir à pratiquer. Les chercheurs ont ensuite relevé leurs blessures sur une période de 21 mois, à partir des dossiers de l'infirmerie sportive de l'établissement." },
      { h: "Les résultats" },
      { p: "Le sommeil était le facteur le plus lié aux blessures. Les jeunes qui dormaient en moyenne moins de 8 heures par nuit avaient environ 1,7 fois plus de risques de se blesser que ceux qui dormaient 8 heures ou plus. Le risque augmentait aussi avec l'âge, au fil des années de lycée, quand les nuits raccourcissent." },
      { p: "Ce type d'étude montre un lien, pas une preuve que le manque de sommeil cause directement les blessures. Mais le résultat va dans le même sens que ce qu'on sait de la récupération : c'est pendant le sommeil que le corps répare les muscles et que la coordination se consolide." },
      { h: "Ce qu'on en retient" },
      { ul: ["Vise 8 à 10 heures de sommeil par nuit si tu as entre 13 et 18 ans, au moins 7 à 9 heures ensuite.", "Garde des horaires réguliers, même le week-end de match.", "Pose le téléphone 30 minutes avant de dormir.", "Après un entraînement tardif, une douche tiède et un repas pas trop lourd aident à s'endormir."] },
      { p: "Le meilleur programme de préparation physique ne remplace pas une bonne nuit : les deux vont ensemble." },
    ],
  },
  {
    slug: "etude-nordic-ischio-jambiers",
    theme: "prevention",
    exos: ["nordic", "pont-une-jambe", "sdt-roumain"],
    title: "Étude : le Nordic, l'exercice qui protège l'arrière des cuisses",
    desc: "Chez 579 footballeurs amateurs, ajouter un seul exercice pendant la saison a divisé par deux environ les blessures des ischio-jambiers.",
    date: "2026-10-19",
    source: {
      cite: "van der Horst N, Smits D-W, Petersen J, Goedhart EA, Backx FJG. The preventive effect of the Nordic hamstring exercise on hamstring injuries in amateur soccer players: a randomized controlled trial. American Journal of Sports Medicine. 2015;43(6):1316-1323.",
      url: "https://pubmed.ncbi.nlm.nih.gov/?term=%22The+preventive+effect+of+the+Nordic+hamstring+exercise+on+hamstring+injuries+in+amateur+soccer+players%22",
      access: "Résumé en libre accès sur PubMed, la base publique des études médicales.",
    },
    body: [
      { p: "Sprinter, freiner, repartir : au handball, les ischio-jambiers, les muscles de l'arrière de la cuisse, travaillent à chaque démarrage et à chaque changement de direction. Une contracture ou une déchirure peut te priver de terrain plusieurs semaines. Un exercice a été particulièrement étudié pour les protéger : le Nordic." },
      { h: "Ce que les chercheurs ont fait" },
      { p: "L'étude a été menée aux Pays-Bas auprès de 579 joueurs de football amateurs, dans 40 équipes. La moitié des équipes a ajouté le Nordic à ses entraînements pendant 13 semaines, puis l'a gardé en entretien le reste de la saison. Les autres équipes se sont entraînées comme d'habitude." },
      { h: "Les résultats" },
      { p: "Dans les équipes qui faisaient le Nordic, il y a eu environ deux fois moins de blessures des ischio-jambiers que dans les autres. L'étude porte sur le football, mais les efforts en cause, sprints et freinages, sont les mêmes au handball." },
      { h: "Comment faire le Nordic" },
      { ul: ["À genoux sur un tapis, les chevilles tenues par un partenaire ou coincées sous un support stable.", "Buste droit, hanches tendues : descends vers l'avant le plus lentement possible, en freinant avec l'arrière des cuisses.", "Rattrape-toi avec les mains quand tu ne peux plus freiner, puis repousse-toi pour remonter.", "Commence par 2 séries de 5 répétitions, 1 à 2 fois par semaine, puis augmente très progressivement."] },
      { h: "Ce qu'on en retient" },
      { ul: ["C'est un exercice difficile : les courbatures des premières séances sont normales, d'où la progression lente.", "Mieux vaut peu, mais toute la saison, que beaucoup pendant deux semaines.", "Le Nordic fait partie de nos programmes, avec des versions plus faciles pour commencer."] },
    ],
  },
  {
    slug: "echauffement-avant-match-handball",
    theme: "saison",
    exos: ["montees-genoux", "fente-laterale", "rotation-externe"],
    title: "L'échauffement avant un match de handball, en 15 minutes",
    desc: "Une routine simple et complète pour être prêt dès l'engagement : activer le corps, préparer les épaules, puis monter en vitesse.",
    date: "2026-11-02",
    body: [
      { p: "Avant un match, le temps sur le terrain est compté et on a vite fait de passer directement aux tirs. Pourtant, les premières minutes de jeu se jouent à pleine vitesse. Voici une routine de 15 minutes, à adapter avec ton coach, qui prépare tout le corps dans le bon ordre." },
      { h: "1. Activer (4 minutes)" },
      { ul: ["Course légère autour du terrain, en variant : pas chassés, talons-fesses, montées de genoux.", "Fentes latérales et ouvertures de hanche pour préparer les adducteurs et les hanches."] },
      { h: "2. Préparer les épaules (3 minutes)" },
      { ul: ["Rotations externes avec un élastique léger, 10 à 15 par bras.", "Grands cercles de bras, puis passes à deux en augmentant peu à peu la distance et la force."] },
      { h: "3. Appuis et réceptions (4 minutes)" },
      { ul: ["Petits sauts sur place, puis réceptions sur une jambe en gardant le genou dans l'axe.", "Changements de direction à vitesse moyenne : 5 mètres, freinage, départ de l'autre côté."] },
      { h: "4. Monter en vitesse (4 minutes)" },
      { ul: ["3 à 4 accélérations de 10 à 15 mètres, de plus en plus vite.", "Tirs progressifs, d'abord à 50 %, puis à pleine puissance.", "Les gardiens : arrêts sur tirs de plus en plus forts, à droite, à gauche, en haut, en bas."] },
      { h: "Les erreurs à éviter" },
      { ul: ["Commencer par les tirs à pleine puissance, épaules froides.", "Faire de longs étirements passifs juste avant le match : ils peuvent faire perdre un peu d'explosivité. Garde-les pour après.", "S'arrêter 15 minutes entre l'échauffement et l'engagement : le corps refroidit. Refais quelques accélérations juste avant."] },
      { p: "Cette routine s'appuie sur les mêmes principes que les programmes de prévention étudiés au handball : équilibre, réceptions et épaules à chaque séance." },
    ],
  },
  {
    slug: "recuperer-entre-deux-matchs-handball",
    theme: "saison",
    exos: ["dead-bug", "hanches-9090", "rotation-thoracique"],
    title: "Récupérer entre deux matchs : ce qui marche vraiment",
    desc: "Sommeil, alimentation, récupération active : les priorités pour être frais au match suivant, sans gadgets.",
    date: "2026-11-16",
    body: [
      { p: "En pleine saison, un match le week-end, parfois deux, et les entraînements reprennent dès le lundi. Bien récupérer, c'est ce qui te permet d'être aussi performant au dernier match qu'au premier. Bonne nouvelle : ce qui marche le mieux est aussi le plus simple." },
      { h: "Priorité n° 1 : le sommeil" },
      { p: "C'est le facteur de récupération le plus puissant, et il est gratuit. La nuit qui suit un match est souvent courte à cause de l'excitation : compense avec une nuit plus longue le lendemain ou une courte sieste de 20 minutes en début d'après-midi." },
      { h: "Priorité n° 2 : boire et manger" },
      { ul: ["Bois régulièrement dans les heures qui suivent le match, surtout si tu as beaucoup transpiré.", "Dans les 2 heures, un vrai repas avec des féculents (pâtes, riz, pain) pour recharger l'énergie et des protéines (viande, poisson, œufs, laitages) pour réparer les muscles."] },
      { h: "Priorité n° 3 : bouger doucement" },
      { p: "Le lendemain du match, une séance légère de 20 à 30 minutes aide souvent davantage que le repos complet : vélo ou footing très tranquille, mobilité des hanches et du haut du dos, gainage doux." },
      { h: "Et le reste ?" },
      { p: "Bains froids, massages, rouleaux : ils peuvent diminuer la sensation de courbatures et faire du bien, mais ils passent après le sommeil et l'alimentation. S'ils t'aident à te sentir mieux, garde-les ; sinon, ne te sens pas obligé." },
      { h: "Quand lever le pied" },
      { ul: ["Si tu te sens anormalement fatigué plusieurs jours de suite.", "Si une douleur apparaît toujours au même endroit.", "Si ton sommeil devient mauvais malgré la fatigue."] },
      { p: "Dans ces cas-là, réduis la charge de ta semaine et parles-en à ton coach. En cas de douleur qui dure, consulte un professionnel de santé." },
    ],
  },
  {
    slug: "treve-noel-handball-garder-la-forme",
    theme: "saison",
    exos: ["squat-jump", "fente-arriere", "planche"],
    title: "Trêve de Noël : garder la forme sans y passer les fêtes",
    desc: "Deux semaines sans handball, ça se prépare : ce que tu perds vraiment, et trois séances courtes par semaine pour reprendre en janvier sans douleur.",
    date: "2026-12-07",
    body: [
      { p: "La trêve de fin d'année est bienvenue : le corps et la tête ont besoin de souffler. Mais deux à trois semaines sans rien faire, et la reprise de janvier peut piquer. La bonne nouvelle : il faut très peu pour garder l'essentiel." },
      { h: "Ce qui se perd, et en combien de temps" },
      { p: "Quelques jours de repos complet ne font rien perdre, ils font même du bien. Au-delà de deux semaines sans activité, c'est surtout l'endurance, ta capacité à répéter les courses, qui baisse en premier. La force et la puissance résistent mieux, à condition de les entretenir un peu." },
      { h: "Le plan simple pour la trêve" },
      { ul: ["Semaine 1 : repos, ou activités plaisir (marche, vélo, autre sport).", "Semaine 2 et suivantes : 3 séances de 25 à 30 minutes par semaine.", "Séance A, jambes : squats, fentes arrière, squats sautés, 3 séries.", "Séance B, course : 2 fois 6 minutes de courses rapides de 15 secondes, avec 15 secondes de marche entre chaque.", "Séance C, gainage et épaules : planche, gainage latéral, rotations externes à l'élastique."] },
      { h: "La veille de la reprise" },
      { p: "Pas de grosse séance pour « rattraper » : un footing tranquille et un peu de mobilité suffisent. Le vrai piège de janvier, c'est de vouloir tout reprendre à 100 % dès le premier entraînement." },
      { p: "Tu préfères un plan déjà écrit ? La 1re partie de saison de 6M Lab va jusqu'à la fin des vacances de Noël, avec deux séances courtes par semaine faciles à caser, et la 2e partie prend le relais pour la reprise de janvier." },
    ],
  },
  {
    slug: "etude-ligament-croise-joueuses-handball",
    theme: "prevention",
    exos: ["saut-reception", "reception-unipodale", "equilibre"],
    title: "Étude : protéger le genou des joueuses de handball",
    desc: "En Norvège, un programme d'équilibre et de réception suivi pendant trois saisons a fait baisser les ruptures du ligament croisé chez les joueuses de l'élite.",
    date: "2026-12-21",
    source: {
      cite: "Myklebust G, Engebretsen L, Braekken IH, Skjølberg A, Olsen O-E, Bahr R. Prevention of anterior cruciate ligament injuries in female team handball players: a prospective intervention study over three seasons. Clinical Journal of Sport Medicine. 2003;13(2):71-78.",
      url: "https://pubmed.ncbi.nlm.nih.gov/?term=%22Prevention+of+anterior+cruciate+ligament+injuries+in+female+team+handball+players%22",
      access: "Résumé en libre accès sur PubMed, la base publique des études médicales.",
    },
    body: [
      { p: "La rupture du ligament croisé antérieur est la blessure la plus redoutée au handball : de longs mois d'arrêt, et parfois une fin de saison. Les joueuses y sont plusieurs fois plus exposées que les joueurs. Elle survient surtout sans contact, lors d'une réception de saut ou d'un changement de direction brusque, quand le genou part vers l'intérieur." },
      { h: "Ce que les chercheurs ont fait" },
      { p: "Une équipe norvégienne a suivi les joueuses des trois premières divisions pendant trois saisons. La première saison servait de comparaison. Les deux suivantes, les équipes ont intégré à leurs entraînements un programme de 15 minutes, 3 fois par semaine pendant la préparation puis une fois par semaine en saison :" },
      { ul: ["des exercices d'équilibre, sur tapis ou plateau instable", "des réceptions de sauts en contrôlant la position du genou", "des changements de direction en apprenant à garder le genou dans l'axe du pied"] },
      { h: "Les résultats" },
      { p: "Dans la première division, chez les joueuses qui suivaient vraiment le programme, les ruptures du ligament croisé ont nettement diminué par rapport à la saison de comparaison. Les chercheurs soulignent qu'un programme ne protège que s'il est fait régulièrement : là où il était peu suivi, l'effet était beaucoup plus faible." },
      { h: "Ce qu'on en retient" },
      { ul: ["La prévention du genou tient en 15 minutes, à intégrer à l'échauffement.", "La clé : apprendre au genou à rester dans l'axe à la réception et dans les appuis.", "La régularité compte plus que tout, toute la saison et pas seulement en préparation.", "C'est pourquoi nos programmes travaillent l'équilibre et les réceptions dès les premières semaines, pour les joueuses comme pour les joueurs."] },
      { p: "Ces conseils sont généraux et ne remplacent pas l'avis d'un professionnel de santé." },
    ],
  },
  {
    slug: "reprise-janvier-apres-la-treve-handball",
    theme: "reprise",
    exos: ["saut-reception", "fente-arriere", "rotation-externe"],
    title: "Reprise de janvier : les deux premières semaines après la trêve",
    desc: "Après deux ou trois semaines de coupure, le corps a besoin de quelques séances pour retrouver son rythme. Comment reprendre sans se blesser.",
    date: "2027-01-04",
    body: [
      { p: "La trêve est finie, la phase retour approche et l'envie de rejouer est là. C'est justement le moment où l'on se blesse le plus facilement : le corps a perdu un peu de ses repères, mais la tête veut tout reprendre à 100 %. Deux semaines bien menées suffisent pour repartir sur de bonnes bases." },
      { h: "Ce qui a changé pendant la trêve" },
      { p: "Si tu as fait les séances courtes de la trêve, tu as gardé l'essentiel. Si tu as tout coupé, ton endurance a un peu baissé, et surtout tes tendons et tes épaules ne sont plus habitués aux centaines de courses, sauts et tirs d'une semaine normale. Ce sont eux qu'il faut ménager en premier." },
      { h: "Semaine 1 : réhabituer le corps" },
      { ul: ["Échauffement complet à chaque séance, sans raccourci : appuis, réceptions, épaules.", "Tirs progressifs : pas de tirs à pleine puissance avant la fin de la semaine.", "Si tu fais du renforcement en plus du club, baisse le volume d'environ un tiers par rapport à avant la trêve.", "Écoute les courbatures : elles sont normales les premiers jours, une douleur qui dure ne l'est pas."] },
      { h: "Semaine 2 : remonter en intensité" },
      { ul: ["Reprends les sprints et les changements de direction à pleine vitesse.", "Retrouve ton volume habituel de renforcement.", "Garde au moins un jour de repos complet entre deux grosses séances."] },
      { h: "Les épaules, le point sensible de janvier" },
      { p: "Une épaule qui reprend d'un coup un grand nombre de tirs est une épaule fragile. Ajoute 5 minutes de rotations externes à l'élastique avant chaque entraînement, et augmente le nombre de tirs sur deux semaines plutôt que dès la première séance. On explique pourquoi dans notre prochain article, étude à l'appui." },
      { p: "Tu veux un plan écrit pour la phase retour ? La 2e partie de saison de 6M Lab propose deux séances courtes par semaine, placées loin des matchs, jusqu'aux phases finales de juin." },
    ],
  },
  {
    slug: "etude-charge-epaule-jeunes-handballeurs",
    theme: "prevention",
    exos: ["rotation-externe", "rotation-externe-haute", "ytw"],
    title: "Étude : augmenter trop vite le volume de handball fragilise l'épaule",
    desc: "Chez 679 jeunes handballeurs et handballeuses de l'élite danoise, une hausse brutale du temps de jeu d'une semaine à l'autre était liée à plus de blessures de l'épaule.",
    date: "2027-01-18",
    source: {
      cite: "Møller M, Nielsen RO, Attermann J, Wedderkopp N, Lind M, Sørensen H, Myklebust G. Handball load and shoulder injury rate: a 31-week cohort study of 679 elite youth handball players. British Journal of Sports Medicine. 2017;51(4):231-237.",
      url: "https://pubmed.ncbi.nlm.nih.gov/?term=%22Handball+load+and+shoulder+injury+rate%22",
      access: "Résumé en libre accès sur PubMed, la base publique des études médicales.",
    },
    body: [
      { p: "Retour de trêve, stage, tournoi, match en retard : il y a des semaines où l'on joue beaucoup plus que d'habitude. Une équipe danoise a voulu savoir si ces hausses brutales comptaient pour l'épaule, l'articulation la plus sollicitée par les tirs." },
      { h: "Ce que les chercheurs ont fait" },
      { p: "679 joueurs et joueuses de 14 à 18 ans, dans des équipes de l'élite jeune au Danemark, ont été suivis pendant 31 semaines de saison. Chaque semaine, ils indiquaient leur temps de handball (entraînements et matchs) et d'éventuels problèmes d'épaule. Leur force et la position de leur omoplate avaient été mesurées au début." },
      { h: "Les résultats" },
      { p: "Les joueurs et joueuses dont le volume de handball augmentait fortement, de plus de 60 % par rapport à la moyenne des quatre semaines précédentes, se blessaient plus souvent à l'épaule. Le risque était encore plus net chez ceux dont les muscles rotateurs externes étaient moins forts, ou dont l'omoplate bougeait mal." },
      { p: "Ce type d'étude montre un lien, pas une preuve que la hausse de charge cause à elle seule la blessure. Mais le message rejoint ce que l'on sait des tendons : ils s'adaptent bien, à condition de leur laisser le temps." },
      { h: "Ce qu'on en retient" },
      { ul: ["Évite les semaines où ton volume de handball fait un bond : après une coupure, remonte sur deux à trois semaines.", "Renforce les rotateurs externes de l'épaule et les muscles de l'omoplate toute la saison, pas seulement en préparation.", "Si tu joues dans deux équipes ou que tu enchaînes les tournois, parles-en à tes coachs pour lisser la charge."] },
      { p: "Ces conseils sont généraux et ne remplacent pas l'avis d'un professionnel de santé." },
    ],
  },
  {
    slug: "phase-retour-garder-sa-puissance-handball",
    theme: "saison",
    exos: ["squat-jump", "squat-bulgare", "departs-10"],
    title: "Phase retour : garder sa puissance jusqu'au dernier match",
    desc: "En février, les jambes commencent à fatiguer et le renforcement passe à la trappe. Le minimum pour rester explosif jusqu'en mai.",
    date: "2027-02-01",
    body: [
      { p: "À mi-saison, beaucoup de joueurs et joueuses arrêtent le renforcement : trop de matchs, trop de fatigue, plus le temps. Résultat, la puissance acquise en préparation s'érode doucement, et on arrive en fin de saison moins explosif qu'en septembre. Pourtant, il en faut très peu pour la garder." },
      { h: "Le principe : l'entretien coûte moins cher que la construction" },
      { p: "Construire de la force demande plusieurs séances par semaine. La garder en demande beaucoup moins : une à deux séances courtes par semaine suffisent, à condition de garder de l'intensité. Ce qu'il faut réduire, c'est le nombre de séries, pas l'effort de chaque répétition." },
      { h: "La séance d'entretien, en 25 minutes" },
      { ul: ["Échauffement : 5 minutes d'appuis et de mobilité.", "Squat jump : 3 séries de 4, en sautant le plus haut possible, récupération complète entre les séries.", "Squat bulgare : 2 à 3 séries de 6 par jambe.", "Départs sur 10 m : 4 à 5 départs à fond, marche retour.", "Gainage : 2 exercices de ton choix."] },
      { p: "Avec des charges ou sans ? À partir de U17 pour les filles et de U18 pour les garçons, un haltère dans chaque main pour le squat bulgare convient si la technique est parfaite. Plus jeune, le poids du corps suffit largement." },
      { h: "Où la placer dans la semaine" },
      { ul: ["Loin du match : idéalement 3 jours avant, jamais la veille.", "Si tu as deux matchs dans la semaine, une seule séance, très courte.", "Après un match difficile, la priorité reste la récupération."] },
      { p: "C'est exactement la logique des 1re et 2e parties de saison : deux séances courtes par semaine pour garder ce que la préparation a construit." },
    ],
  },
  {
    slug: "vacances-fevrier-handball-semaine-sans-club",
    theme: "saison",
    exos: ["pogos", "fente-laterale", "gainage-lateral"],
    title: "Vacances de février : une semaine sans club, que faire ?",
    desc: "Le gymnase ferme pour les vacances ? Profite de la coupure pour souffler, et garde trois petites habitudes pour revenir en forme.",
    date: "2027-02-15",
    body: [
      { p: "Pendant les vacances d'hiver, beaucoup de clubs ferment le gymnase une semaine ou deux. Ce n'est pas une mauvaise nouvelle : en pleine phase retour, une semaine plus légère fait souvent du bien au corps comme à la tête. Il suffit de ne pas tout couper." },
      { h: "Une semaine : repos actif" },
      { ul: ["Garde 2 séances de 20 à 25 minutes dans la semaine.", "Fais une autre activité que tu aimes : vélo, natation, ski, un autre sport de balle.", "Dors plus : c'est le meilleur moment pour rattraper le sommeil en retard."] },
      { h: "Deux semaines : un peu plus de rythme" },
      { ul: ["Séance A, appuis : pogos, fentes latérales, sauts sur une jambe, 3 séries.", "Séance B, course : 2 fois 6 minutes de 15 secondes rapides et 15 secondes de marche.", "Séance C, gainage : gainage latéral, planche, Pallof press si tu as un élastique."] },
      { h: "Au retour" },
      { p: "Les mêmes règles qu'en janvier, en plus court : un premier entraînement sans tirs à pleine puissance, et un volume qui remonte sur quelques jours plutôt que d'un coup. Une semaine de coupure ne fait presque rien perdre ; c'est le retour trop brutal qui coûte cher." },
    ],
  },
  {
    slug: "etude-equilibre-entorses-cheville",
    theme: "prevention",
    exos: ["equilibre", "equilibre-balle", "reception-unipodale"],
    title: "Étude : l'équilibre sur une jambe contre les entorses de cheville",
    desc: "Dans un sport de sauts proche du handball, un programme d'équilibre fait à l'entraînement a réduit les entorses de cheville, surtout chez ceux qui s'en étaient déjà fait une.",
    date: "2027-03-01",
    source: {
      cite: "Verhagen E, van der Beek A, Twisk J, Bouter L, Bahr R, van Mechelen W. The effect of a proprioceptive balance board training program for the prevention of ankle sprains: a prospective controlled trial. American Journal of Sports Medicine. 2004;32(6):1385-1393.",
      url: "https://pubmed.ncbi.nlm.nih.gov/?term=%22The+effect+of+a+proprioceptive+balance+board+training+program+for+the+prevention+of+ankle+sprains%22",
      access: "Résumé en libre accès sur PubMed, la base publique des études médicales.",
    },
    body: [
      { p: "L'entorse de cheville est la blessure la plus courante au handball : une réception sur le pied d'un adversaire, un appui qui tourne, et c'est parti pour plusieurs semaines. Et une fois qu'on s'en est fait une, le risque de récidive augmente. Une étude néerlandaise a testé un moyen simple de la prévenir." },
      { h: "Ce que les chercheurs ont fait" },
      { p: "L'étude a été menée auprès d'équipes de volley-ball, un sport où l'on saute et où l'on retombe près des autres, comme au handball. Une partie des équipes a intégré un programme d'exercices d'équilibre à ses entraînements pendant une saison, sur une jambe, au sol puis sur un plateau instable, avec ou sans ballon. Les autres équipes se sont entraînées comme d'habitude." },
      { h: "Les résultats" },
      { p: "Les équipes qui suivaient le programme ont eu moins d'entorses de cheville. L'effet était surtout net chez les joueurs et joueuses qui s'étaient déjà fait une entorse auparavant : pour eux, le travail d'équilibre protégeait nettement contre la récidive." },
      { h: "Ce qu'on en retient" },
      { ul: ["Tiens sur une jambe, genou légèrement fléchi : 3 fois 30 secondes par jambe suffisent pour commencer.", "Complique peu à peu : yeux fermés, sur un coussin, en lançant une balle contre un mur.", "Ajoute des réceptions sur une jambe, en tenant 3 secondes.", "Si tu t'es déjà fait une entorse, ces exercices sont encore plus importants pour toi.", "Après une entorse récente, fais-toi d'abord examiner par un professionnel de santé."] },
      { p: "L'équilibre et les réceptions font partie de chaque séance de nos programmes, dès l'échauffement." },
    ],
  },
  {
    slug: "gardien-handball-hanches-fin-de-saison",
    theme: "performance",
    exos: ["cosaque", "copenhague", "adduction"],
    title: "Gardiens de but : 3 exercices pour garder des hanches souples jusqu'en fin de saison",
    desc: "Grands écarts, parades basses, appuis latéraux : les hanches et les adducteurs des gardiens souffrent en fin de saison. Dix minutes deux fois par semaine pour les entretenir.",
    date: "2027-03-15",
    body: [
      { p: "Le gardien ou la gardienne de but fait des mouvements que personne d'autre ne fait sur le terrain : écarts brusques, parades pied en l'air, appuis latéraux à répétition. En mars, après des mois de matchs, les hanches se raidissent et les adducteurs, à l'intérieur des cuisses, deviennent sensibles. Un petit entretien régulier change tout." },
      { h: "1. Squat cosaque : la souplesse en mouvement" },
      { p: "Pieds très écartés, descends sur une jambe en gardant l'autre tendue, puis passe de l'autre côté sans te relever. 2 séries de 6 passages. Descends seulement aussi bas que possible sans douleur à l'aine." },
      { h: "2. Gainage Copenhague : la force de l'intérieur des cuisses" },
      { p: "Sur le côté, jambe du dessus posée sur un banc, monte le bassin et tiens. 2 séries de 15 à 20 secondes par côté, genou sur le banc pour commencer. C'est l'un des exercices les plus étudiés pour protéger les adducteurs." },
      { h: "3. Adduction avec ballon : l'activation express" },
      { p: "Allongé sur le dos, un ballon entre les genoux, serre fort 5 secondes puis relâche. 5 répétitions. Idéal en échauffement, juste avant les arrêts." },
      { h: "Quand les faire" },
      { ul: ["Deux fois par semaine, loin du match, en 10 minutes.", "L'adduction avec ballon peut se glisser dans chaque échauffement.", "Une douleur à l'aine qui revient à chaque séance mérite l'avis d'un professionnel de santé, avant qu'elle ne s'installe."] },
      { p: "Pour aller plus loin, notre guide de la préparation physique du gardien de but reprend ces exercices et bien d'autres, saison par saison." },
    ],
  },
];

// Scheduled publishing: an article dated in the future stays hidden (list, page, sitemap) until
// that day, then shows up on its own (the pages are rebuilt every hour at most).
const today = () => new Date().toISOString().slice(0, 10);
export const isLive = (p: Post) => p.date <= today();
export const livePosts = () => posts.filter(isLive);

// About 200 words per minute.
export const readTime = (p: Post) =>
  Math.max(1, Math.round(p.body.map((b) => ("h" in b ? b.h : "p" in b ? b.p : b.ul.join(" "))).join(" ").split(/\s+/).length / 200));
